const genres = [
	"Fantasy",
	"Science Fiction",
	"Dystopian",
	"Adventure",
	"Mystery",
	"Thriller",
	"Horror",
	"Romance",
	"Historical Fiction",
	"Contemporary",
	"Magical Realism",
	"Urban Fantasy",
	"Paranormal",
	"Biography",
	"Memoir",
	"Self-Help",
	"True Crime",
	"Essay",
	"Journalism",
	"Philosophy",
	"Science",
	"Psychology",
	"History",
	"Politics",
	"Economics",
	"Religion & Spirituality",
	"Travel",
	"Health & Wellness",
	"Business & Finance",
	"Education",
	"Young Adult (YA)",
	"Middle Grade",
	"Children's Literature",
	"Picture Books",
	"Fairytales & Folklore",
	"Classics",
	"Poetry",
	"Anthology",
	"Drama / Plays",
	"Graphic Novels / Comics",
	"Short Stories",
	"Satire",
	"Epistolary",
	"African Literature",
	"Asian Literature",
	"Latin American Literature",
	"Middle Eastern Literature",
	"Indigenous Literature",
	"European Classics",
	"LGBTQ+ Literature",
	"Feminist Literature",
	"Historical Romance",
	"Sci-Fi Romance",
	"Cozy Mystery",
	"Dark Fantasy",
	"Cyberpunk",
	"Steampunk",
	"Gothic Fiction",
	"Speculative Fiction",
	"Apocalyptic / Post-Apocalyptic",
	"Time Travel",
	"Mythology & Retellings",
	"Christian Fiction",
	"War Stories",
	"Campus Novels",
];

export default genres;
